### ISSUE TITLE
No serial connection when HDMI connected first

### ISSUE THREAD

**Issue by JetA2** [SzymonSlupik/CEC-Tiny-Pro#1]
Hi! 

Thank you for this project, very cool.
I built it with a Beetle and it works out of the box.
I'm using it as a passive CEC monitor.

My problem is that I can only get it to work if I connect the USB serial first and then connect the HDMI.
If I connect HDMI first, I can see the blue LED on the Beetle pulsing but when I then connect the USB cable the port does not show up in the Arduino IDE.

If I understand the code correctly it should wait until the serial is active before starting the loop but this does not seem to happen.
What could be the issue?

**Comment by JetA2** [comment]
I tested on a Raspberry Pi with picocom instead of the Arduino IDE on my Mac and it works.
Maybe some issue with the Mac environment or the Arduino IDE.

**Comment by SzymonSlupik** [comment]
I wonder though how it is powered when the USB port is not connected?
Anyway if I remember correctly, Beetle does some USB port profile switching when the Arduino IDE uploads a project. So as you point out, it may be the host side USB drivers are not fully compatible with that.

**Comment by JetA2** [comment]
It's powered through the HDMI port isn't it?
But there must also be some power priority logic happening since I now have it powered both through the HDMI port and the USB. I've no idea which of them the Arduino chooses, but it works :)

**Comment by SzymonSlupik** [comment]
Yes but not sure about the Beetle USB/Serial port if that too receives power from the VCC pin/pad. Which may than somehow influence the USB-side behavior. But it clearly is related to your configuration, as I have not seen that effect on my setup (I'm using Windows).
